environment:
  buildroot:      /build/BUILDROOT
  source:
    prefix:       /build/SOURCES
    lib-path:     /build/SOURCES/library
    module-path:  /build/SOURCES/modules
    patch-path:   /build/SOURCES/patches
  vm:
    prefix:       /build/BUILDROOT/vm
    include:      /build/BUILDROOT/vm/include
    lib-path:     /build/BUILDROOT/vm/lib
    lua-include:  /build/BUILDROOT/vm/include/luajit
    lua-cmodule:  /build/BUILDROOT/vm/lib/lua
  cpu:
    sse4_2: False
    pclmul: False
